# Generated by Django 6.0 on 2025-12-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='x',
            table='X',
        ),
    ]
