# Generated by Django 6.0 on 2025-12-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0002_alter_x_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='x',
            table='x',
        ),
    ]
